const MAPS = {
    "stone": ["http://media-mcw.cursecdn.com/a/a6/Grid_Stone.png", "http://www.minecraftwiki.net/wiki/Stone", "Stone"],
    "stone_brick": ["http://media-mcw.cursecdn.com/1/1c/Grid_Stone_Brick.png", "http://www.minecraftwiki.net/wiki/Stone_brick", "Stone Brick"],
    "stone_brick_cracked": ["http://media-mcw.cursecdn.com/8/85/Grid_Cracked_Stone_Brick.png", "http://www.minecraftwiki.net/wiki/Stone_brick", "Cracked Stone Brick"],
    "stone_brick_mossy": ["http://media-mcw.cursecdn.com/2/23/Grid_Mossy_Stone_Brick.png", "http://www.minecraftwiki.net/wiki/Stone_brick", "Mossy Stone Brick"],
    "stone_brick_chiseled": ["http://media-mcw.cursecdn.com/7/7b/Grid_Chiseled_Stone_Brick.png", "http://www.minecraftwiki.net/wiki/Stone_brick", "Chiseled Stone Brick"],
    "dirt": ["http://media-mcw.cursecdn.com/b/bd/Grid_Dirt.png", "http://www.minecraftwiki.net/wiki/Dirt", "Dirt"],
    "cobblestone": ["http://media-mcw.cursecdn.com/0/03/Grid_Cobblestone.png", "http://www.minecraftwiki.net/wiki/Cobblestone", "Cobblestone"],
    "planks": ["http://media-mcw.cursecdn.com/9/9f/Grid_Wooden_Plank.png", "http://www.minecraftwiki.net/wiki/Planks", "Planks"],
    "saplings": ["http://media-mcw.cursecdn.com/b/b5/Grid_Sapling.png", "http://www.minecraftwiki.net/wiki/Sapling", "Sapling"],
    "bedrock": ["http://media-mcw.cursecdn.com/e/e0/Grid_Bedrock.png", "http://www.minecraftwiki.net/wiki/Bedrock", "Bedrock"],
    "water_block": ["http://media-mcw.cursecdn.com/1/13/Grid_Water.png", "http://www.minecraftwiki.net/wiki/Water", "Water Block"],
    "lava_block": ["http://media-mcw.cursecdn.com/6/61/Grid_Lava.png", "http://www.minecraftwiki.net/wiki/Lava", "Lava Block"],
    "sand": ["http://media-mcw.cursecdn.com/b/bb/Grid_Sand.png", "http://www.minecraftwiki.net/wiki/Sand", "Sand"],
    "gravel": ["http://media-mcw.cursecdn.com/0/03/Grid_Gravel.png", "http://www.minecraftwiki.net/wiki/Gravel", "Gravel"],
    "gold_ore": ["http://media-mcw.cursecdn.com/5/5c/Grid_Gold_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Gold_Ore", "Gold Ore"],
    "iron_ore": ["http://media-mcw.cursecdn.com/7/74/Grid_Iron_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Iron_ore", "Iron Ore"],
    "coal_ore": ["http://media-mcw.cursecdn.com/8/8c/Grid_Coal_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Coal_ore", "Coal Ore"],
    "wood": ["http://media-mcw.cursecdn.com/b/bf/Grid_Wood.png", "http://www.minecraftwiki.net/wiki/Wood", "Wood"],
    "leaves": ["http://media-mcw.cursecdn.com/3/30/Grid_Leaves.png", "http://www.minecraftwiki.net/wiki/Leaves", "Leaves"],
    "sponge": ["http://media-mcw.cursecdn.com/5/56/Grid_Sponge.png", "http://www.minecraftwiki.net/wiki/Sponge", "Sponge"],
    "glass": ["http://media-mcw.cursecdn.com/0/00/Grid_Glass.png", "http://www.minecraftwiki.net/wiki/Glass", "Glass"],
    "lapis_ore": ["http://media-mcw.cursecdn.com/d/d2/Grid_Lapis_Lazuli_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Lapis_Lazuli_Ore", "Lapis Lazuli"],
    "dispenser": ["http://media-mcw.cursecdn.com/c/cc/Grid_Dispenser.png", "http://www.minecraftwiki.net/wiki/Dispenser", "Dispenser"],
    "sandstone": ["http://media-mcw.cursecdn.com/1/12/Grid_Sandstone.png", "http://www.minecraftwiki.net/wiki/Sandstone", "Sandstone"],
    "noteblock": ["http://media-mcw.cursecdn.com/1/1d/Grid_Note_Block.png", "http://www.minecraftwiki.net/wiki/Noteblock", "Noteblock"],
    "bed": ["http://media-mcw.cursecdn.com/a/a3/Grid_Bed.png", "http://www.minecraftwiki.net/wiki/Bed", "Bed"],
    "rail": ["http://media-mcw.cursecdn.com/7/7a/Grid_Rails.png", "http://www.minecraftwiki.net/wiki/Rail", "Minecart Track"],
    "rail_powered": ["http://media-mcw.cursecdn.com/9/9d/Grid_Powered_Rail.png", "http://www.minecraftwiki.net/wiki/Powered_Rail", "Powered Rail"],
    "rail_detector": ["http://media-mcw.cursecdn.com/a/a2/Grid_Detector_Rail.png", "http://www.minecraftwiki.net/wiki/Detector_Rail", "Detector Rail"],
    "piston": ["http://media-mcw.cursecdn.com/3/3c/Grid_Piston.png", "http://www.minecraftwiki.net/wiki/Piston", "Piston"],
    "piston_sticky": ["http://media-mcw.cursecdn.com/3/32/Grid_Sticky_Piston.png", "http://www.minecraftwiki.net/wiki/Piston", "Sticky Piston"],
    "web": ["http://media-mcw.cursecdn.com/3/36/Grid_Cobweb.png", "http://www.minecraftwiki.net/wiki/Web", "Cobweb"],

    "wool_white": ["http://media-mcw.cursecdn.com/f/fa/Grid_White_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Wool"],
    "wool_orange": ["http://media-mcw.cursecdn.com/0/07/Grid_Orange_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Orange Wool"],
    "wool_magenta": ["http://media-mcw.cursecdn.com/f/fd/Grid_Magenta_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Magenta Wool"],
    "wool_lightblue": ["http://media-mcw.cursecdn.com/f/fb/Grid_Light_Blue_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Light Blue Wool"],
    "wool_yellow": ["http://media-mcw.cursecdn.com/e/ed/Grid_Yellow_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Yellow Wool"],
    "wool_limegreen": ["http://media-mcw.cursecdn.com/a/a2/Grid_Lime_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Lime Green Wool"],
    "wool_pink": ["http://media-mcw.cursecdn.com/b/b3/Grid_Pink_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Pink Wool"],
    "wool_gray": ["http://media-mcw.cursecdn.com/d/d3/Grid_Gray_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Gray Wool"],
    "wool_lightgray": ["http://media-mcw.cursecdn.com/e/e5/Grid_Light_Gray_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Light Gray Wool"],
    "wool_cyan": ["http://media-mcw.cursecdn.com/c/cd/Grid_Cyan_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Cyan Wool"],
    "wool_purple": ["http://media-mcw.cursecdn.com/5/51/Grid_Purple_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Purple Wool"],
    "wool_blue": ["http://media-mcw.cursecdn.com/4/40/Grid_Blue_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Blue Wool"],
    "wool_brown": ["http://media-mcw.cursecdn.com/2/2a/Grid_Brown_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Brown Wool"],
    "wool_green": ["http://media-mcw.cursecdn.com/f/fa/Grid_Green_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Green Wool"],
    "wool_red": ["http://media-mcw.cursecdn.com/2/2a/Grid_Red_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Red Wool"],
    "wool_black": ["http://media-mcw.cursecdn.com/4/45/Grid_Black_Wool.png", "http://www.minecraftwiki.net/wiki/Wool", "Black Wool"],

    "flower_red": ["http://media-mcw.cursecdn.com/4/49/Grid_Rose.png", "http://www.minecraftwiki.net/wiki/Flower#Rose", "Rose"],
    "flower_yellow": ["http://media-mcw.cursecdn.com/4/49/Grid_Dandelion.png", "http://www.minecraftwiki.net/wiki/Flower#Dandelion", "Dandelion"],
    "mushroom_brown": ["http://media-mcw.cursecdn.com/d/d8/Grid_Brown_Mushroom.png", "http://www.minecraftwiki.net/wiki/Mushrooms", "Brown Mushroom"],
    "mushroom_red": ["http://media-mcw.cursecdn.com/0/01/Grid_Red_Mushroom.png", "http://www.minecraftwiki.net/wiki/Mushrooms", "Red Mushroom"],
    "gold_block": ["http://media-mcw.cursecdn.com/b/b6/Grid_Gold_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Gold_block", "Gold Block"],
    "iron_block": ["http://media-mcw.cursecdn.com/5/5a/Grid_Iron_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Iron_block", "Iron Block"],

    "slab_stone": ["http://media-mcw.cursecdn.com/2/29/Grid_Stone_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Stone Half-Slab"],
    "slab_wooden": ["http://media-mcw.cursecdn.com/5/5c/Grid_Oak_Wood_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Wooden Half-Slab"],
    "slab_spruce": ["http://media-mcw.cursecdn.com/6/60/Grid_Spruce_Wood_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Spruce Wood Half-Slab"],
    "slab_birch": ["http://media-mcw.cursecdn.com/b/bc/Grid_Birch_Wood_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Birch Wood Half-Slab"],
    "slab_jungle": ["http://media-mcw.cursecdn.com/3/3f/Grid_Jungle_Wood_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Jungle Wood Half-Slab"],
    "slab_cobblestone": ["http://media-mcw.cursecdn.com/f/f7/Grid_Cobblestone_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Cobblestone Half-Slab"],
    "slab_sandstone": ["http://media-mcw.cursecdn.com/2/2a/Grid_Sandstone_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Sandstone Half-Slab"],
    "slab_brick": ["http://media-mcw.cursecdn.com/b/b3/Grid_Bricks_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Brick Stairs"],
    "slab_brick_stone": ["http://media-mcw.cursecdn.com/4/46/Grid_Stone_Bricks_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Stone Brick Stairs"],
    "slab_brick_nether": ["http://media-mcw.cursecdn.com/d/dd/Grid_Nether_Brick_Slab.png", "http://www.minecraftwiki.net/wiki/Slab", "Nether Brick Stairs"],

    "brick_block": ["http://media-mcw.cursecdn.com/6/64/Grid_Brick_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Bricks", "Bricks"],
    "tnt": ["http://media-mcw.cursecdn.com/2/2b/Grid_TNT.png", "http://www.minecraftwiki.net/wiki/TNT", "TNT"],
    "bookshelf": ["http://media-mcw.cursecdn.com/b/bc/Grid_Bookshelf.png", "http://www.minecraftwiki.net/wiki/Bookshelf", "Bookshelf"],
    "cobblestone_mossy": ["http://media-mcw.cursecdn.com/7/7d/Grid_Moss_Stone.png", "http://www.minecraftwiki.net/wiki/Moss_Stone", "Mossy Cobblestone"],
    "obsidian": ["http://media-mcw.cursecdn.com/5/5d/Grid_Obsidian.png", "http://www.minecraftwiki.net/wiki/Obsidian", "Obsidian"],
    "torch": ["http://media-mcw.cursecdn.com/3/32/Grid_Torch.png", "http://www.minecraftwiki.net/wiki/Torch", "Torch"],
    "fire": ["http://media-mcw.cursecdn.com/c/c6/Grid_Fire.png", "http://www.youtube.com/watch?v=gkLvpt9Z3fA", "Fire"],
    "spawner": ["http://media-mcw.cursecdn.com/3/3b/Grid_Monster_Spawner.png", "http://www.minecraftwiki.net/wiki/Spawner", "Mob Spawner"],

    "stairs_wooden": ["http://media-mcw.cursecdn.com/3/3b/Grid_Wooden_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Wooden Stairs"],
    "stairs_jungle": ["http://media-mcw.cursecdn.com/b/b9/Grid_Jungle_Wood_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Jungle Wood Stairs"],
    "stairs_birch": ["http://media-mcw.cursecdn.com/d/de/Grid_Birch_Wood_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Birch Wood Stairs"],
    "stairs_spruce": ["http://media-mcw.cursecdn.com/2/24/Grid_Spruce_Wood_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Spruce Wood Stairs"],
    "stairs_cobblestone": ["http://media-mcw.cursecdn.com/7/7f/Grid_Cobblestone_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Cobblestone Stairs"],
    "stairs_brick": ["http://media-mcw.cursecdn.com/3/3c/Grid_Brick_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Brick Stairs"],
    "stairs_brick_stone": ["http://media-mcw.cursecdn.com/a/af/Grid_Stone_Brick_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Stone Brick Stairs"],
    "stairs_brick_nether": ["http://media-mcw.cursecdn.com/6/68/Grid_Nether_Brick_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Nether Brick Stairs"],
    "stairs_sandstone": ["http://media-mcw.cursecdn.com/0/0d/Grid_Sandstone_Stairs.png", "http://www.minecraftwiki.net/wiki/Stairs", "Sandstone Bricks"],

    "chest": ["http://media-mcw.cursecdn.com/c/c1/Grid_Chest.png", "http://www.minecraftwiki.net/wiki/Chest", "Chest"],
    "diamond_ore": ["http://media-mcw.cursecdn.com/e/ef/Grid_Diamond_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Diamond_Ore", "Diamond Ore"],
    "diamond_block": ["http://media-mcw.cursecdn.com/7/73/Grid_Diamond_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Diamond_block", "Diamond Block"],
    "crafting_table": ["http://media-mcw.cursecdn.com/7/79/Grid_Crafting_Table.png", "http://www.minecraftwiki.net/wiki/Crafting_bench", "Crafting Table"],
    "farmland": ["http://media-mcw.cursecdn.com/6/6a/Grid_Farmland.png", "http://www.minecraftwiki.net/wiki/Farmland", "Farmland"],
    "furnace": ["http://media-mcw.cursecdn.com/2/2e/Grid_Furnace.png", "http://www.minecraftwiki.net/wiki/Furnace", "Furnace"],
    "door_wood": ["http://media-mcw.cursecdn.com/c/cd/Grid_Wooden_Door.png", "http://www.minecraftwiki.net/wiki/Door", "Wooden Door"],
    "door_iron": ["http://media-mcw.cursecdn.com/2/27/Grid_Iron_Door.png", "http://www.minecraftwiki.net/wiki/Door", "Iron Door"],
    "lever": ["http://media-mcw.cursecdn.com/3/33/Grid_Lever.png", "http://www.minecraftwiki.net/wiki/Lever", "Lever"],
    "pressure_plate_wood": ["http://media-mcw.cursecdn.com/d/d4/Grid_Wooden_Pressure_Plate.png", "http://www.minecraftwiki.net/wiki/Pressure_Plate", "Wooden Pressure Plate"],
    "pressure_plate_stone": ["http://media-mcw.cursecdn.com/4/46/Grid_Stone_Pressure_Plate.png", "http://www.minecraftwiki.net/wiki/Pressure_Plate", "Stone Pressure Plate"],
    "redstone_ore": ["http://media-mcw.cursecdn.com/b/b8/Grid_Redstone_%28Ore%29.png", "http://www.minecraftwiki.net/wiki/Redstone_Ore", "Redstone Ore"],
    "redstone_torch": ["http://media-mcw.cursecdn.com/6/66/Grid_Redstone_%28Torch%29.png", "http://www.minecraftwiki.net/wiki/Redstone_Torch", "Redstone Torch"],
    "button_stone": ["http://media-mcw.cursecdn.com/8/81/Grid_Stone_Button.png", "http://www.minecraftwiki.net/wiki/Button", "Stone Button"],
    "button_wooden": ["http://media-mcw.cursecdn.com/c/c6/Grid_Wooden_Button.png", "http://www.minecraftwiki.net/wiki/Button", "Wooden Button"],
    "snow": ["http://media-mcw.cursecdn.com/6/6c/Grid_Snow.png", "http://www.minecraftwiki.net/wiki/Snow", "Snow"],
    "snow_block": ["http://media-mcw.cursecdn.com/6/66/Grid_Snow_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Snow_block", "Snow Block"],
    "ice": ["http://media-mcw.cursecdn.com/2/2e/Grid_Ice.png", "http://www.minecraftwiki.net/wiki/Ice", "Ice"],
    "cactus": ["http://media-mcw.cursecdn.com/f/fb/Grid_Cactus.png", "http://www.minecraftwiki.net/wiki/Cactus", "Cactus"],
    "clay_block": ["http://media-mcw.cursecdn.com/a/a6/Grid_Clay_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Clay_block", "Clay Block"],
    "sugarcane": ["http://media-mcw.cursecdn.com/d/d3/Grid_Sugar_Cane.png", "http://www.minecraftwiki.net/wiki/Sugar_Cane", "Sugar Cane"],
    "jukebox": ["http://media-mcw.cursecdn.com/1/10/Grid_Jukebox.png", "http://www.minecraftwiki.net/wiki/Jukebox", "Jukebox"],
    "fence": ["http://media-mcw.cursecdn.com/c/c8/Grid_Fence.png", "http://www.minecraftwiki.net/wiki/Fence", "Fence"],
    "pumpkin": ["http://media-mcw.cursecdn.com/b/be/Grid_Pumpkin.png", "http://www.minecraftwiki.net/wiki/Pumpkin", "Pumpkin"],
    "netherrack": ["http://media-mcw.cursecdn.com/8/86/Grid_Netherrack.png", "http://www.minecraftwiki.net/wiki/Netherrack", "Netherrack"],
    "soul_sand": ["http://media-mcw.cursecdn.com/e/e4/Grid_Soul_Sand.png", "http://www.minecraftwiki.net/wiki/Soul_Sand", "Soul Sand"],
    "glowstone_block": ["http://media-mcw.cursecdn.com/f/fd/Grid_Glowstone_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Glowstone", "Glowstone"],
    "jack_o_lantern": ["http://media-mcw.cursecdn.com/a/ac/Grid_Jack-O-Lantern.png", "http://www.minecraftwiki.net/wiki/Jack_%27o%27_Lantern", "Jack 'o' Lantern"],
    "cake": ["http://media-mcw.cursecdn.com/2/28/Grid_Cake.png", "http://www.minecraftwiki.net/wiki/Cake", "Cake"],
    "redstone_repeater": ["http://media-mcw.cursecdn.com/b/b0/Grid_Redstone_%28Repeater%29.png", "http://www.minecraftwiki.net/wiki/Redstone_Repeater", "Redstone Repeater"],
    "trapdoor": ["http://media-mcw.cursecdn.com/b/b2/Grid_Trapdoor.png", "http://www.minecraftwiki.net/wiki/Trap_Door", "Trap Door"],
    "iron_bars": ["http://media-mcw.cursecdn.com/0/00/Grid_Iron_Bars.png", "http://www.minecraftwiki.net/wiki/Iron_Bars", "Iron Bars"],
    "glass_pane": ["http://media-mcw.cursecdn.com/3/30/Grid_Glass_Pane.png", "http://www.minecraftwiki.net/wiki/Glass-pane", "Glass Pane"],
    "melon_block": ["http://media-mcw.cursecdn.com/0/09/Grid_Melon_%28Block%29.png", "http://www.minecraftwiki.net/wiki/Melon_(Block)", "Melon Block"],
    "vine": ["http://media-mcw.cursecdn.com/2/29/Grid_Vines.png", "http://www.minecraftwiki.net/wiki/Vine", "Vine"],
    "fence_gate": ["http://media-mcw.cursecdn.com/c/c2/Grid_Fence_Gate.png", "http://www.minecraftwiki.net/wiki/Fence_gate", "Fence Gate"],
    "mycelium": ["http://media-mcw.cursecdn.com/a/aa/Grid_Mycelium.png", "http://www.minecraftwiki.net/wiki/Mycelium", "Mycelium"],
    "lily_pad": ["http://media-mcw.cursecdn.com/4/49/Grid_Lily_Pad.png", "http://www.minecraftwiki.net/wiki/Lily_Pad", "Lily Pad"],
    "nether_brick": ["http://media-mcw.cursecdn.com/6/62/Grid_Nether_Brick.png", "http://www.minecraftwiki.net/wiki/Nether_brick", "Nether Brick"],
    "nether_fence": ["http://media-mcw.cursecdn.com/5/59/Grid_Nether_Brick_Fence.png", "http://www.minecraftwiki.net/wiki/Nether_Brick_Fence", "Nether Brick Fence"],
    "nether_wart": ["http://media-mcw.cursecdn.com/f/f2/Grid_Nether_Wart_Seeds.png", "http://www.minecraftwiki.net/wiki/Nether_Wart", "Nether Wart"],
    "enchantment_table": ["http://media-mcw.cursecdn.com/0/00/Grid_Enchantment_Table.png", "http://www.minecraftwiki.net/wiki/Enchantment_Table", "Enchantment Table"],
    "brewing_stand": ["http://media-mcw.cursecdn.com/7/70/Grid_Brewing_Stand.png", "http://www.minecraftwiki.net/wiki/Brewing_stand", "Brewing Stand"],
    "cauldron": ["http://media-mcw.cursecdn.com/c/ca/Grid_Cauldron.png", "http://www.minecraftwiki.net/wiki/Cauldron", "Cauldron"],
    "dragon_egg": ["http://media-mcw.cursecdn.com/b/b1/Grid_Dragon_Egg.png", "http://www.minecraftwiki.net/wiki/Dragon_Egg", "Dragon Egg"],
    "redstone_lamp": ["http://media-mcw.cursecdn.com/f/fa/Grid_Redstone_Lamp.png", "http://www.minecraftwiki.net/wiki/Redstone_lamp", "Redstone Lamp"],
    "emerald_ore": ["http://media-mcw.cursecdn.com/e/e7/Grid_Emerald_Ore.png", "http://www.minecraftwiki.net/wiki/Emerald_ore", "Emerald Ore"],
    "ender_chest": ["http://media-mcw.cursecdn.com/5/56/Grid_Ender_Chest.png", "http://www.minecraftwiki.net/wiki/Ender_chest", "Ender Chest"],
    "emerald_block": ["http://media-mcw.cursecdn.com/2/27/Grid_Block_of_Emerald.png", "http://www.minecraftwiki.net/wiki/Emerald_block", "Emerald Block"],
    "command_block": ["http://media-mcw.cursecdn.com/d/de/Grid_Adventure_Mode_Control_Block.png", "http://www.minecraftwiki.net/wiki/Command_Block", "Command Block"],
    "beacon": ["http://media-mcw.cursecdn.com/c/cb/Grid_Beacon.png", "http://www.minecraftwiki.net/wiki/Beacon", "Beacon"],
    "cobblestone_wall": ["http://media-mcw.cursecdn.com/a/a9/Grid_Cobblestone_Wall.png", "http://www.minecraftwiki.net/wiki/Cobblestone_wall", "Cobblestone Wall"],
    "cobblestone_wall_mossy": ["http://media-mcw.cursecdn.com/6/63/Grid_Mossy_Cobblestone_Wall.png", "http://www.minecraftwiki.net/wiki/Cobblestone_wall", "Mossy Cobblestone Wall"],
    "mob_head_human": ["http://media-mcw.cursecdn.com/5/55/Grid_Head.png", "http://www.minecraftwiki.net/wiki/Mob_head", "Human Mob Head"],
    "mob_head_creeper": ["http://media-mcw.cursecdn.com/c/c7/Grid_Creeper_Head.png", "http://www.minecraftwiki.net/wiki/Mob_head", "Creeper Mob Head"],
    "mob_head_zombie": ["http://media-mcw.cursecdn.com/6/6f/Grid_Zombie_Head.png", "http://www.minecraftwiki.net/wiki/Mob_head", "Zombie Mob Head"],
    "mob_head_skeleton": ["http://media-mcw.cursecdn.com/c/c9/Grid_Skeleton_Skull.png", "http://www.minecraftwiki.net/wiki/Mob_head", "Skeleton Mob Head"],
    "mob_head_wither": ["http://media-mcw.cursecdn.com/d/d4/Grid_Wither_Skeleton_Skull.png", "http://www.minecraftwiki.net/wiki/Mob_head", "Wither Skeleton Mob Head"],
    "anvil": ["http://media-mcw.cursecdn.com/1/13/Grid_Anvil.png", "http://www.minecraftwiki.net/wiki/Anvil", "Anvil"],

    "sword_wood": ["http://media-mcw.cursecdn.com/c/cf/Grid_Wooden_Sword.png", "http://www.minecraftwiki.net/wiki/Sword", "Wooden Sword"],
    "sword_stone": ["http://media-mcw.cursecdn.com/e/e1/Grid_Stone_Sword.png", "http://www.minecraftwiki.net/wiki/Sword", "Stone Sword"],
    "sword_iron": ["http://media-mcw.cursecdn.com/d/d5/Grid_Iron_Sword.png", "http://www.minecraftwiki.net/wiki/Sword", "Iron Sword"],
    "sword_gold": ["http://media-mcw.cursecdn.com/1/1f/Grid_Gold_Sword.png", "http://www.minecraftwiki.net/wiki/Sword", "Gold Sword"],
    "sword_diamond": ["http://media-mcw.cursecdn.com/8/81/Grid_Diamond_Sword.png", "http://www.minecraftwiki.net/wiki/Sword", "Diamond Sword"],
    "pickaxe_wood": ["http://media-mcw.cursecdn.com/3/3d/Grid_Wooden_Pickaxe.png", "http://www.minecraftwiki.net/wiki/Pickaxe", "Wooden Pickaxe"],
    "pickaxe_stone": ["http://media-mcw.cursecdn.com/d/d2/Grid_Stone_Pickaxe.png", "http://www.minecraftwiki.net/wiki/Pickaxe", "Stone Pickaxe"],
    "pickaxe_iron": ["http://media-mcw.cursecdn.com/1/1d/Grid_Iron_Pickaxe.png", "http://www.minecraftwiki.net/wiki/Pickaxe", "Iron Pickaxe"],
    "pickaxe_gold": ["http://media-mcw.cursecdn.com/9/95/Grid_Gold_Pickaxe.png", "http://www.minecraftwiki.net/wiki/Pickaxe", "Gold Pickaxe"],
    "pickaxe_diamond": ["http://media-mcw.cursecdn.com/c/ce/Grid_Diamond_Pickaxe.png", "http://www.minecraftwiki.net/wiki/Pickaxe", "Diamond Pickaxe"],
    "shovel_wood": ["http://media-mcw.cursecdn.com/2/21/Grid_Wooden_Shovel.png", "http://www.minecraftwiki.net/wiki/Shovel", "Wooden Shovel"],
    "shovel_stone": ["http://media-mcw.cursecdn.com/f/ff/Grid_Stone_Shovel.png", "http://www.minecraftwiki.net/wiki/Shovel", "Stone Shovel"],
    "shovel_iron": ["http://media-mcw.cursecdn.com/0/01/Grid_Iron_Shovel.png", "http://www.minecraftwiki.net/wiki/Shovel", "Iron Shovel"],
    "shovel_gold": ["http://media-mcw.cursecdn.com/8/85/Grid_Gold_Shovel.png", "http://www.minecraftwiki.net/wiki/Shovel", "Gold Shovel"],
    "shovel_diamond": ["http://media-mcw.cursecdn.com/8/8e/Grid_Diamond_Shovel.png", "http://www.minecraftwiki.net/wiki/Shovel", "Diamond Shovel"],
    "axe_wood": ["http://media-mcw.cursecdn.com/2/2a/Grid_Wooden_Axe.png", "http://www.minecraftwiki.net/wiki/Axe", "Wooden Axe"],
    "axe_stone": ["http://media-mcw.cursecdn.com/5/55/Grid_Stone_Axe.png", "http://www.minecraftwiki.net/wiki/Axe", "Stone Axe"],
    "axe_iron": ["http://media-mcw.cursecdn.com/1/1d/Grid_Iron_Axe.png", "http://www.minecraftwiki.net/wiki/Axe", "Iron Axe"],
    "axe_gold": ["http://media-mcw.cursecdn.com/9/99/Grid_Gold_Axe.png", "http://www.minecraftwiki.net/wiki/Axe", "Gold Axe"],
    "axe_diamond": ["http://media-mcw.cursecdn.com/8/8d/Grid_Diamond_Axe.png", "http://www.minecraftwiki.net/wiki/Axe", "Diamond Axe"],
    "hoe_wood": ["http://media-mcw.cursecdn.com/e/ea/Grid_Wooden_Hoe.png", "http://www.minecraftwiki.net/wiki/Hoe", "Wooden Hoe"],
    "hoe_stone": ["http://media-mcw.cursecdn.com/b/ba/Grid_Stone_Hoe.png", "http://www.minecraftwiki.net/wiki/Hoe", "Stone Hoe"],
    "hoe_iron": ["http://media-mcw.cursecdn.com/f/f8/Grid_Iron_Hoe.png", "http://www.minecraftwiki.net/wiki/Hoe", "Iron Hoe"],
    "hoe_gold": ["http://media-mcw.cursecdn.com/7/77/Grid_Gold_Hoe.png", "http://www.minecraftwiki.net/wiki/Hoe", "Gold Hoe"],
    "hoe_diamond": ["http://media-mcw.cursecdn.com/c/c9/Grid_Diamond_Hoe.png", "http://www.minecraftwiki.net/wiki/Hoe", "Diamond Hoe"],
    "armor_helmet_chain": ["http://media-mcw.cursecdn.com/c/cf/Grid_Chain_Armor_Helmet.png", "http://www.minecraftwiki.net/wiki/Helmet#Helmets", "Chain Helmet"],
    "armor_helmet_leather": ["http://media-mcw.cursecdn.com/2/24/Grid_Leather_Cap.png", "http://www.minecraftwiki.net/wiki/Helmet#Helmets", "Leather Helmet"],
    "armor_helmet_iron": ["http://media-mcw.cursecdn.com/e/ec/Grid_Iron_Helmet.png", "http://www.minecraftwiki.net/wiki/Helmet#Helmets", "Iron Helmet"],
    "armor_helmet_gold": ["http://media-mcw.cursecdn.com/3/3a/Grid_Gold_Helmet.png", "http://www.minecraftwiki.net/wiki/Helmet#Helmets", "Gold Helmet"],
    "armor_helmet_diamond": ["http://media-mcw.cursecdn.com/b/bd/Grid_Diamond_Helmet.png", "http://www.minecraftwiki.net/wiki/Helmet#Helmets", "Diamond Helmet"],
    "armor_chest_chain": ["http://media-mcw.cursecdn.com/f/f4/Grid_Chain_Armor_Chestplate.png", "http://www.minecraftwiki.net/wiki/Chestplate#Chestplates", "Chain Chestplate"],
    "armor_chest_leather": ["http://media-mcw.cursecdn.com/e/ed/Grid_Leather_Tunic.png", "http://www.minecraftwiki.net/wiki/Chestplate#Chestplates", "Leather Chestplate"],
    "armor_chest_iron": ["http://media-mcw.cursecdn.com/8/8d/Grid_Iron_Chestplate.png", "http://www.minecraftwiki.net/wiki/Chestplate#Chestplates", "Iron Chestplate"],
    "armor_chest_gold": ["http://media-mcw.cursecdn.com/7/7b/Grid_Gold_Chestplate.png", "http://www.minecraftwiki.net/wiki/Chestplate#Chestplates", "Gold Chestplate"],
    "armor_chest_diamond": ["http://media-mcw.cursecdn.com/e/e7/Grid_Diamond_Chestplate.png", "http://www.minecraftwiki.net/wiki/Chestplate#Chestplates", "Diamond Chestplate"],
    "armor_legs_chain": ["http://media-mcw.cursecdn.com/1/1b/Grid_Chain_Armor_Leggings.png", "http://www.minecraftwiki.net/wiki/Leggings#Leggings", "Chain Leggings"],
    "armor_legs_leather": ["http://media-mcw.cursecdn.com/c/ce/Grid_Leather_Pants.png", "http://www.minecraftwiki.net/wiki/Leggings#Leggings", "Leather Leggings"],
    "armor_legs_iron": ["http://media-mcw.cursecdn.com/9/99/Grid_Iron_Leggings.png", "http://www.minecraftwiki.net/wiki/Leggings#Leggings", "Iron Leggings"],
    "armor_legs_gold": ["http://media-mcw.cursecdn.com/f/f5/Grid_Gold_Leggings.png", "http://www.minecraftwiki.net/wiki/Leggings#Leggings", "Gold Leggings"],
    "armor_legs_diamond": ["http://media-mcw.cursecdn.com/e/e3/Grid_Diamond_Leggings.png", "http://www.minecraftwiki.net/wiki/Leggings#Leggings", "Diamond Leggings"],
    "armor_boots_chain": ["http://media-mcw.cursecdn.com/7/74/Grid_Chain_Armor_Boots.png", "http://www.minecraftwiki.net/wiki/Boots#Boots", "Chain Boots"],
    "armor_boots_leather": ["http://media-mcw.cursecdn.com/0/06/Grid_Leather_Boots.png", "http://www.minecraftwiki.net/wiki/Boots#Boots", "Leather Boots"],
    "armor_boots_iron": ["http://media-mcw.cursecdn.com/f/f5/Grid_Iron_Boots.png", "http://www.minecraftwiki.net/wiki/Boots#Boots", "Iron Boots"],
    "armor_boots_gold": ["http://media-mcw.cursecdn.com/0/00/Grid_Gold_Boots.png", "http://www.minecraftwiki.net/wiki/Boots#Boots", "Gold Boots"],
    "armor_boots_diamond": ["http://media-mcw.cursecdn.com/d/d1/Grid_Diamond_Boots.png", "http://www.minecraftwiki.net/wiki/Boots#Boots", "Diamond Boots"],
    "flint_and_steel": ["http://media-mcw.cursecdn.com/f/fb/Grid_Flint_and_Steel.png", "http://www.minecraftwiki.net/wiki/Flint_and_Steel", "Flint and Steel"],
    "apple": ["http://media-mcw.cursecdn.com/3/39/Grid_Red_Apple.png", "http://www.minecraftwiki.net/wiki/Apple", "Apple"],
    "bow": ["http://media-mcw.cursecdn.com/4/49/Grid_Bow.png", "http://www.minecraftwiki.net/wiki/Bow", "Bow"],
    "arrow": ["http://media-mcw.cursecdn.com/c/cc/Grid_Arrow.png", "http://www.minecraftwiki.net/wiki/Arrow", "Arrow"],
    "coal": ["http://media-mcw.cursecdn.com/1/1c/Grid_Coal_%28Item%29.png", "http://www.minecraftwiki.net/wiki/Coal", "Coal"],
    "diamond": ["http://media-mcw.cursecdn.com/c/cf/Grid_Diamond_%28Gem%29.png", "http://www.minecraftwiki.net/wiki/Diamond", "Diamond"],
    "iron_ingot": ["http://media-mcw.cursecdn.com/c/c6/Grid_Iron_%28Ingot%29.png", "http://www.minecraftwiki.net/wiki/Iron_ingot", "Iron Ingot"],
    "gold_ingot": ["http://media-mcw.cursecdn.com/6/62/Grid_Gold_%28Ingot%29.png", "http://www.minecraftwiki.net/wiki/Gold_ingot", "Gold Ingot"],
    "stick": ["http://media-mcw.cursecdn.com/e/e9/Grid_Stick.png", "http://www.minecraftwiki.net/wiki/Stick", "Stick"],
    "bowl": ["http://media-mcw.cursecdn.com/f/f1/Grid_Bowl.png", "http://www.minecraftwiki.net/wiki/Bowl", "Bowl"],
    "mushroom_soup": ["http://media-mcw.cursecdn.com/f/fd/Grid_Mushroom_Stew.png", "http://www.minecraftwiki.net/wiki/Mushroom_Stew", "Mushroom Stew"],
    "string": ["http://media-mcw.cursecdn.com/f/fa/Grid_String.png", "http://www.minecraftwiki.net/wiki/String", "String"],
    "feather": ["http://media-mcw.cursecdn.com/a/a7/Grid_Feather.png", "http://www.minecraftwiki.net/wiki/Feather", "Feather"],
    "gunpowder": ["http://media-mcw.cursecdn.com/7/7a/Grid_Gunpowder.png", "http://www.minecraftwiki.net/wiki/Gunpowder", "Gunpowder"],
    "seeds_wheat": ["http://media-mcw.cursecdn.com/6/68/Grid_Seeds.png", "http://www.minecraftwiki.net/wiki/Wheat_Seeds", "Wheat Seeds"],
    "wheat": ["http://media-mcw.cursecdn.com/c/c4/Grid_Wheat.png", "http://www.minecraftwiki.net/wiki/Wheat", "Wheat"],
    "bread": ["http://media-mcw.cursecdn.com/d/d4/Grid_Bread.png", "http://www.mincraftwiki.net/wiki/Bread", "Bread"],
    "flint": ["http://media-mcw.cursecdn.com/8/82/Grid_Flint.png", "http://www.minecraftwiki.net/wiki/Flint", "Flint"],
    "porkchop_raw": ["http://media-mcw.cursecdn.com/e/ec/Grid_Raw_Porkchop.png", "http://www.minecraftwiki.net/wiki/Raw_Porkchop", "Raw Porkchop"],
    "porkchop_cooked": ["http://media-mcw.cursecdn.com/b/bd/Grid_Cooked_Porkchop.png", "http://www.minecraftwiki.net/wiki/Cooked_Porkchop", "Cooked Porkchop"],
    "painting": ["http://media-mcw.cursecdn.com/c/cc/Grid_Painting.png", "http://www.minecraftwiki.net/wiki/Painting", "Painting"],
    "golden_apple": ["http://media-mcw.cursecdn.com/4/4e/Grid_Golden_Apple.png", "http://www.minecraftwiki.net/wiki/Golden_apple", "Golden Apple"],
    "sign": ["http://media-mcw.cursecdn.com/0/06/Grid_Sign.png", "http://www.minecraftwiki.net/wiki/Sign", "Sign"],
    "bucket": ["http://media-mcw.cursecdn.com/2/2a/Grid_Bucket.png", "http://www.minecraftwiki.net/wiki/Bucket", "Bucket"],
    "bucket_water": ["http://media-mcw.cursecdn.com/b/bf/Grid_Water_Bucket.png", "http://www.minecraftwiki.net/wiki/Water#Water_Bucket", "Water Bucket"],
    "bucket_lava": ["http://media-mcw.cursecdn.com/c/cf/Grid_Lava_Bucket.png", "http://www.minecraftwiki.net/wiki/Lava#Lava_Bucket", "Lava Bucket"],
    "milk": ["http://media-mcw.cursecdn.com/6/63/Grid_Milk_Bucket.png", "http://www.minecraftwiki.net/wiki/Milk", "Milk"],
    "minecart": ["http://media-mcw.cursecdn.com/5/58/Grid_Minecart.png", "http://www.minecraftwiki.net/wiki/Minecart", "Minecart"],
    "minecart_chest": ["http://media-mcw.cursecdn.com/f/fa/Grid_Storage_Minecart.png", "http://www.minecraftwiki.net/wiki/Minecart_with_Chest", "Chest Minecart"],
    "minecart_furnace": ["http://media-mcw.cursecdn.com/7/7f/Grid_Powered_Minecart.png", "http://www.minecraftwiki.net/wiki/Minecart_with_Furnace", "Powered Minecart"],
    "saddle": ["http://media-mcw.cursecdn.com/0/09/Grid_Saddle.png", "http://www.minecraftwiki.net/wiki/Saddle", "Saddle"],
    "redstone_dust": ["http://media-mcw.cursecdn.com/c/c3/Grid_Redstone_%28Dust%29.png", "http://www.minecraftwiki.net/wiki/Redstone_dust", "Redstone Dust"],
    "snowball": ["http://media-mcw.cursecdn.com/6/67/Grid_Snowball.png", "http://www.minecraftwiki.net/wiki/Snowball", "Snowball"],
    "boat": ["http://media-mcw.cursecdn.com/5/59/Grid_Boat.png", "http://www.minecraftwiki.net/wiki/Boat", "Boat"],
    "leather": ["http://media-mcw.cursecdn.com/6/66/Grid_Leather.png", "http://www.minecraftwiki.net/wiki/Leather", "Leather"],
    "brick": ["http://media-mcw.cursecdn.com/e/ed/Grid_Clay_%28Brick%29.png", "http://www.minecraftwiki.net/wiki/Brick", "Brick"],
    "clay": ["http://media-mcw.cursecdn.com/3/38/Grid_Clay_%28Item%29.png", "http://www.minecraftwiki.net/wiki/Clay", "Clay"],
    "paper": ["http://media-mcw.cursecdn.com/6/6c/Grid_Paper.png", "http://www.minecraftwiki.net/wiki/Paper", "Paper"],
    "book": ["http://media-mcw.cursecdn.com/e/ec/Grid_Book.png", "http://www.minecraftwiki.net/wiki/Book", "Book"],
    "slimeball": ["http://media-mcw.cursecdn.com/c/c9/Grid_Slimeball.png", "http://www.minecraftwiki.net/wiki/Slimeball", "Slimeball"],
    "egg_chicken": ["http://media-mcw.cursecdn.com/2/27/Grid_Egg.png", "http://www.minecraftwiki.net/wiki/Chicken_Egg", "Chicken Egg"],
    "compass": ["http://media-mcw.cursecdn.com/f/f2/Grid_Compass.png", "http://www.minecraftwiki.net/wiki/Compass", "Compass"],
    "fishing_rod": ["http://media-mcw.cursecdn.com/c/c7/Grid_Fishing_Rod.png", "http://www.minecraftwiki.net/wiki/Fishing_Rod", "Fishing Rod"],
    "clock": ["http://media-mcw.cursecdn.com/3/32/Grid_Clock.png", "http://www.minecraftwiki.net/wiki/Clock", "Clock"],
    "glowstone_dust": ["http://media-mcw.cursecdn.com/2/2c/Grid_Glowstone_%28Dust%29.png", "http://www.minecraftwiki.net/wiki/Glowstone_Dust", "Glowstone Dust"],
    "fish_raw": ["http://media-mcw.cursecdn.com/6/6a/Grid_Raw_Fish.png", "http://www.minecraftwiki.net/wiki/Raw_Fish", "Raw Fish"],
    "fish_cooked": ["http://media-mcw.cursecdn.com/2/29/Grid_Cooked_Fish.png", "http://www.minecraftwiki.net/wiki/Cooked_Fish", "Cooked Fish"],

    "dye_white": ["http://media-mcw.cursecdn.com/c/c0/Grid_Bone_Meal.png", "http://www.minecraftwiki.net/wiki/Bone_Meal", "Bone Meal"],
    "dye_orange": ["http://media-mcw.cursecdn.com/b/b2/Grid_Orange_Dye.png", "http://www.minecraftwiki.net/wiki/Orange_Dye", "Orange Dye"],
    "dye_magenta": ["http://media-mcw.cursecdn.com/8/8f/Grid_Magenta_Dye.png", "http://www.minecraftwiki.net/wiki/Magenta_Dye", "Magenta Dye"],
    "dye_light_blue": ["http://media-mcw.cursecdn.com/a/ae/Grid_Light_Blue_Dye.png", "http://www.minecraftwiki.net/wiki/Light_Blue_Dye", "Light Blue Dye"],
    "dye_yellow": ["http://media-mcw.cursecdn.com/d/df/Grid_Dandelion_Yellow.png", "http://www.minecraftwiki.net/wiki/Dandelion_Yellow", "Dandelion Yellow"],
    "dye_lime_green": ["http://media-mcw.cursecdn.com/a/a6/Grid_Lime_Dye.png", "http://www.minecraftwiki.net/wiki/Lime_Dye", "Lime Green Dye"],
    "dye_pink": ["http://media-mcw.cursecdn.com/b/bb/Grid_Pink_Dye.png", "http://www.minecraftwiki.net/wiki/Pink_Dye", "Pink Dye"],
    "dye_gray": ["http://media-mcw.cursecdn.com/5/54/Grid_Gray_Dye.png", "http://www.minecraftwiki.net/wiki/Gray_Dye", "Gray Dye"],
    "dye_light_gray": ["http://media-mcw.cursecdn.com/1/16/Grid_Light_Gray_Dye.png", "http://www.minecraftwiki.net/wiki/Light_Gray_Dye", "Light Gray Dye"],
    "dye_cyan": ["http://media-mcw.cursecdn.com/c/ca/Grid_Cyan_Dye.png", "http://www.minecraftwiki.net/wiki/Cyan_Dye", "Cyan Dye"],
    "dye_purple": ["http://media-mcw.cursecdn.com/a/a0/Grid_Purple_Dye.png", "http://www.minecraftwiki.net/wiki/Purple_Dye", "Purple Dye"],
    "dye_blue": ["http://media-mcw.cursecdn.com/a/a8/Grid_Lapis_Lazuli_%28Dye%29.png", "http://www.minecraftwiki.net/wiki/Lapis_Lazuli", "Lapis Lazuil"],
    "dye_brown": ["http://media-mcw.cursecdn.com/7/7d/Grid_Cocoa_Beans.png", "http://www.minecraftwiki.net/wiki/Cocoa_Beans", "Cocoa Beans"],
    "dye_green": ["http://media-mcw.cursecdn.com/f/fd/Grid_Cactus_Green.png", "http://www.minecraftwiki.net/wiki/Cactus_Green", "Cactus Green"],
    "dye_red": ["http://media-mcw.cursecdn.com/0/0d/Grid_Rose_Red.png", "http://www.minecraftwiki.net/wiki/Rose_Red", "Rose Red"],
    "dye_black": ["http://media-mcw.cursecdn.com/d/d6/Grid_Ink_Sac.png", "http://www.minecraftwiki.net/wiki/Ink_Sac", "Ink Sac"],
    "ink_sac": ["http://media-mcw.cursecdn.com/d/d6/Grid_Ink_Sac.png", "http://www.minecraftwiki.net/wiki/Ink_Sac", "Ink Sac"],
    "bonemeal": ["http://media-mcw.cursecdn.com/c/c0/Grid_Bone_Meal.png", "http://www.minecraftwiki.net/wiki/Bone_Meal", "Bonemeal"],
    "cocoa_beans": ["http://media-mcw.cursecdn.com/7/7d/Grid_Cocoa_Beans.png", "http://www.minecraftwiki.net/wiki/Cocoa_Beans", "Cocoa Beans"],
    "lapis_lazuli": ["http://media-mcw.cursecdn.com/a/a8/Grid_Lapis_Lazuli_%28Dye%29.png", "http://www.minecraftwiki.net/wiki/Lapis_Lazuli", "Lapis Lazuil"],
    "cactus_green": ["http://media-mcw.cursecdn.com/f/fd/Grid_Cactus_Green.png", "http://www.minecraftwiki.net/wiki/Cactus_Green", "Cactus Green"],

    "bone": ["http://media-mcw.cursecdn.com/e/e8/Grid_Bone.png", "http://www.minecraftwiki.net/wiki/Bone", "Bone"],
    "cookie": ["http://media-mcw.cursecdn.com/9/95/Grid_Cookie.png", "http://www.minecraftwiki.net/wiki/Cookie", "Cookie"],
    "map": ["http://media-mcw.cursecdn.com/3/33/Grid_Map_%28Item%29.png", "http://www.minecraftwiki.net/wiki/Map_(item)", "Map"],
    "shears": ["http://media-mcw.cursecdn.com/1/13/Grid_Shears.png", "http://www.minecraftwiki.net/wiki/Shears", "Shears"],
    "melon_slice": ["http://media-mcw.cursecdn.com/e/ee/Grid_Melon_%28Slice%29.png", "http://www.minecraftwiki.net/wiki/Melon_Slice", "Melon Slice"],
    "melon_slice_glistering": ["http://media-mcw.cursecdn.com/1/11/Grid_Glistering_Melon.png", "http://www.minecraftwiki.net/wiki/Glistering_Melon", "Glistering Melon"],
    "seeds_pumpkin": ["http://media-mcw.cursecdn.com/7/72/Grid_Pumpkin_Seeds.png", "http://www.minecraftwiki.net/wiki/Pumpkin_Seeds", "Pumpkin Seeds"],
    "seeds_melon": ["http://media-mcw.cursecdn.com/7/75/Grid_Melon_Seeds.png", "http://www.minecraftwiki.net/wiki/Melon_Seeds", "Melon Seeds"],
    "beef_raw": ["http://media-mcw.cursecdn.com/6/61/Grid_Raw_Beef.png", "http://www.minecraftwiki.net/wiki/Raw_Beef", "Raw Beef"],
    "beef_cooked": ["http://media-mcw.cursecdn.com/d/da/Grid_Steak.png", "http://www.minecraftwiki.net/wiki/Cooked_Beef", "Cooked Beef"],
    "chicken_raw": ["http://media-mcw.cursecdn.com/e/e5/Grid_Raw_Chicken.png", "http://www.minecraftwiki.net/wiki/Raw_Chicken", "Raw Chicken"],
    "chicken_cooked": ["http://media-mcw.cursecdn.com/2/2e/Grid_Cooked_Chicken.png", "http://www.minecraftwiki.net/wiki/Cooked_Chicken", "Cooked Chicken"],
    "rotten_flesh": ["http://media-mcw.cursecdn.com/3/33/Grid_Rotten_Flesh.png", "http://www.minecraftwiki.net/wiki/Rotten_Flesh", "Rotten Flesh"],
    "ender_pearl": ["http://media-mcw.cursecdn.com/1/13/Grid_Ender_Pearl.png", "http://www.minecraftwiki.net/wiki/Ender_Pearl", "Ender Pearl"],
    "blaze_rod": ["http://media-mcw.cursecdn.com/1/18/Grid_Blaze_Rod.png", "http://www.minecraftwiki.net/wiki/Blaze_Rod", "Blaze Rod"],
    "ghast_tear": ["http://media-mcw.cursecdn.com/6/66/Grid_Ghast_Tear.png", "http://www.minecraftwiki.net/wiki/Ghast_Tear", "Ghast Tear"],
    "gold_nugget": ["http://media-mcw.cursecdn.com/1/1d/Grid_Gold_Nugget.png", "http://media-mcw.cursecdn.com/6/66/Grid_Ghast_Tear.png", "Gold Nugget"],
    "glass_bottle": ["http://media-mcw.cursecdn.com/2/22/Grid_Glass_Bottle.png", "http://www.minecraftwiki.net/wiki/Glass_Bottle", "Glass Bottle"],
    "spider_eye": ["http://media-mcw.cursecdn.com/0/03/Grid_Spider_Eye.png", "http://www.minecraftwiki.net/wiki/Spider_Eye", "Spider Eye"],
    "spider_eye_fermented": ["http://media-mcw.cursecdn.com/2/29/Grid_Fermented_Spider_Eye.png", "http://www.minecraftwiki.net/wiki/Fermented_Spider_Eye", "Fermented Spider Eye"],
    "blaze_powder": ["http://media-mcw.cursecdn.com/0/09/Grid_Blaze_Powder.png", "http://www.minecraftwiki.net/wiki/Blaze_Powder", "Blaze Powder"],
    "magma_cream": ["http://media-mcw.cursecdn.com/e/e8/Grid_Magma_Cream.png", "http://www.minecraftwiki.net/wiki/Magma_Cream", "Magma Cream"],
    "eye_of_ender": ["http://media-mcw.cursecdn.com/0/0e/Grid_Eye_of_Ender.png", "http://www.minecraftwiki.net/wiki/Eye_of_Ender", "Eye of Ender"],
    "fire_charge": ["http://media-mcw.cursecdn.com/e/e1/Grid_Fire_Charge.png", "http://www.minecraftwiki.net/wiki/Fire_Charge", "Fire Charge"],
    "book_and_quill": ["http://media-mcw.cursecdn.com/e/eb/Grid_Book_and_Quill.png", "http://www.minecraftwiki.net/wiki/Book_and_Quill", "Book and Quill"],
    "emerald": ["http://media-mcw.cursecdn.com/8/87/Grid_Emerald.png", "http://www.minecraftwiki.net/wiki/Emerald", "Emerald"],
    "item_frame": ["http://media-mcw.cursecdn.com/c/c5/Grid_Item_Frame.png", "http://www.minecraftwiki.net/wiki/Item_Frame", "Item Frame"],
    "flower_pot": ["http://media-mcw.cursecdn.com/8/89/Grid_Flower_Pot.png", "http://www.minecraftwiki.net/wiki/Flower_Pot", "Flower Pot"],
    "carrot": ["http://media-mcw.cursecdn.com/8/8b/Grid_Carrot.png", "http://www.minecraftwiki.net/wiki/Carrot", "Carrot"],
    "carrot_golden": ["http://media-mcw.cursecdn.com/a/a7/Grid_Golden_Carrot.png", "http://www.minecraftwiki.net/wiki/Golden_Carrot", "Golden Carrot"],
    "carrot_stick": ["http://media-mcw.cursecdn.com/e/e4/Grid_Carrot_on_a_Stick.png", "http://www.minecraftwiki.net/wiki/Carrot_on_a_Stick", "Carrot on a Stick"],
    "potato": ["http://media-mcw.cursecdn.com/2/2b/Grid_Potato.png", "http://www.minecraftwiki.net/wiki/Potato", "Potato"],
    "potato_baked": ["http://media-mcw.cursecdn.com/6/6c/Grid_Baked_Potato.png", "http://www.minecraftwiki.net/wiki/Baked_Potato", "Baked Potato"],
    "potato_poisonous": ["http://media-mcw.cursecdn.com/f/fd/Grid_Poisonous_Potato.png", "http://www.minecraftwiki.net/wiki/Poisonous_Potato", "Poisonous Potato"],
    "nether_star": ["http://media-mcw.cursecdn.com/a/ae/Grid_Nether_Star.png", "http://www.minecraftwiki.net/wiki/Nether_Star", "Nether Star"],
    "pumpkin_pie": ["http://media-mcw.cursecdn.com/9/9f/Grid_Pumpkin_Pie.png", "http://www.minecraftwiki.net/wiki/Pumpkin_Pie", "Pumpkin Pie"],

    "record_13": ["http://media-mcw.cursecdn.com/5/55/Grid_Gold_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "13 Record"],
    "record_cat": ["http://media-mcw.cursecdn.com/c/c4/Grid_Green_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Cat Record"],
    "record_blocks": ["http://media-mcw.cursecdn.com/4/4d/Grid_Blocks_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Blocks Record"],
    "record_chirp": ["http://media-mcw.cursecdn.com/b/be/Grid_Chirp_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Chrip Record"],
    "record_far": ["http://media-mcw.cursecdn.com/9/9e/Grid_Far_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Far Record"],
    "record_mall": ["http://media-mcw.cursecdn.com/b/b8/Grid_Mall_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Mall Record"],
    "record_mellohi": ["http://media-mcw.cursecdn.com/7/7a/Grid_Mellohi_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Mellohi Record"],
    "record_stal": ["http://media-mcw.cursecdn.com/1/1d/Grid_Stal_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Stal Record"],
    "record_strad": ["http://media-mcw.cursecdn.com/a/aa/Grid_Strad_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Strad Record"],
    "record_ward": ["http://media-mcw.cursecdn.com/d/da/Grid_Ward_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Ward Record"],
    "record_11": ["http://media-mcw.cursecdn.com/e/e4/Grid_11_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "11 Record"],
    "record_wait": ["http://media-mcw.cursecdn.com/6/67/Grid_wait_Disc.png", "http://www.minecraftwiki.net/wiki/Records", "Wait Record"],

    "assembly_I": ["http://trains-and-zeppelin.wikispaces.com/file/view/assemblyI.png/396822270/assemblyI.png", "", "Assembly Table I"],
    "assembly_II": ["http://trains-and-zeppelin.wikispaces.com/file/view/assemblyII.png/396822282/assemblyII.png", "", "Assembly Table II"],
    "assembly_III": ["http://trains-and-zeppelin.wikispaces.com/file/view/assemblyIII.png/396822292/assemblyIII.png", "", "Assembly Table III"],
    "distil": ["http://trains-and-zeppelin.wikispaces.com/file/view/distil.png/396822306/distil.png", "", "Distillation Tower"],
    "oil_sands": ["http://trains-and-zeppelin.wikispaces.com/file/view/oilsands.png/396822318/oilsands.png", "", "Oil Sands"],
    "crude_oil": ["http://trains-and-zeppelin.wikispaces.com/file/view/petroleum.png/396822326/petroleum.png", "", "Crude Oil"],
    "rail_detector_loco": ["http://trains-and-zeppelin.wikispaces.com/file/view/LocomotiveDetector.png", "", "Locomotive Detector"],
    "rail_detector_passenger": ["http://trains-and-zeppelin.wikispaces.com/file/view/PassengerDetectorRail.png/396822352/PassengerDetectorRail.png", "", "Passenger Detector"],
    "rail_detector_freight": ["http://trains-and-zeppelin.wikispaces.com/file/view/FreightDetectorRail.png/396822342/FreightDetectorRail.png", "", "Freight Detector"],
    "rail_coupler": ["http://trains-and-zeppelin.wikispaces.com/file/view/CouplerRail.png", "", "Coupler Rail"],
    "train_workbench": ["http://trains-and-zeppelin.wikispaces.com/file/view/trainworkbench.png/396822370/trainworkbench.png", "", "Train Workbench"],

    "diesel_can": ["http://trains-and-zeppelin.wikispaces.com/file/view/Items_05.png/394557780/Items_05.png", "", "Diesel Can"],
    "stake": ["http://trains-and-zeppelin.wikispaces.com/file/view/Stake.png/394557982/Stake.png", "", "Stake"],
    "dust_steel": ["http://trains-and-zeppelin.wikispaces.com/file/view/SteelDust.png", "", "Steel Dust"],
    "dust_coal": ["http://trains-and-zeppelin.wikispaces.com/file/view/CoalDust.png/394557858/CoalDust.png", "", "Coal Dust"],
    "graphite": ["http://trains-and-zeppelin.wikispaces.com/file/view/Graphite.png", "", "Graphite"],
    "boiler": ["http://trains-and-zeppelin.wikispaces.com/file/view/boilerItem.png/344077958/boilerItem.png", "", "Boiler"],
    "firebox": ["http://trains-and-zeppelin.wikispaces.com/file/view/fireboxItem.png/344077990/fireboxItem.png", "", "Firebox"],
    "steel_wheel": ["http://trains-and-zeppelin.wikispaces.com/file/view/bogieItem.png/343992752/bogieItem.png", "", "Steel Wheel"],
    "steel_frame": ["http://trains-and-zeppelin.wikispaces.com/file/view/steelFrameItem.png/344076328/steelFrameItem.png", "", "Steel Frame"],
    "steel_cab": ["http://trains-and-zeppelin.wikispaces.com/file/view/cabinItem.png/344077968/cabinItem.png", "", "Steel Cab"],
    "steel_chimney": ["http://trains-and-zeppelin.wikispaces.com/file/view/chimneyItem.png/344076992/chimneyItem.png", "", "Steel Chimney"],
    "zeppelin": ["http://trains-and-zeppelin.wikispaces.com/file/view/zeppelinItem.png/344077948/zeppelinItem.png", "", "Zeppelin"],
    "balloon": ["http://trains-and-zeppelin.wikispaces.com/file/view/balloonItem.png/344077954/balloonItem.png", "", "Balloon"],
    "propeller": ["http://trains-and-zeppelin.wikispaces.com/file/view/propellerItem.png/344075152/propellerItem.png", "", "Propeller"],
    "steam_engine": ["http://trains-and-zeppelin.wikispaces.com/file/view/steamEngineItem.png/344077926/steamEngineItem.png", "", "Steam Engine"],
    "diesel_engine": ["http://trains-and-zeppelin.wikispaces.com/file/view/dieselEngineItem.png/344077988/dieselEngineItem.png", "", "Diesel Engine"],
    "engine_piston": ["http://trains-and-zeppelin.wikispaces.com/file/view/pistonItem.png/344077922/pistonItem.png", "", "Piston"],
    "camshaft": ["http://trains-and-zeppelin.wikispaces.com/file/view/camshaftItem.png/344077976/camshaftItem.png", "", "Camshaft"],
    "cylinder": ["http://trains-and-zeppelin.wikispaces.com/file/view/cylinderItem.png/344077978/cylinderItem.png", "", "Cylinder"],
    "electric_motor": ["http://trains-and-zeppelin.wikispaces.com/file/view/electMotorItem.png/344073438/electMotorItem.png", "", "Electric Motor"],
    "wood_frame": ["http://trains-and-zeppelin.wikispaces.com/file/view/Items_98.png/394558250/Items_98.png", "", "Wooden Frame"],
    "wood_wheel": ["http://trains-and-zeppelin.wikispaces.com/file/view/Items_99.png/394558256/Items_99.png", "", "Wooden Wheel"],
    "wood_cab": ["http://trains-and-zeppelin.wikispaces.com/file/view/woodCab.png/394558262/woodCab.png", "", "Wooden Cab"],
    "iron_chimney": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_Chimney.png/394558268/iron_Chimney.png", "", "Iron Chimney"],
    "iron_firebox": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_Firebox.png/394558272/iron_Firebox.png", "", "Iron Firebox"],
    "iron_boiler": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_Boiler.png/394558278/iron_Boiler.png", "", "Iron Boiler"],
    "iron_frame": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_Frame.png/394558452/iron_Frame.png", "", "Iron Frame"],
    "iron_wheel": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_wheel.png/394558456/iron_wheel.png", "", "Iron Wheel"],
    "iron_cab": ["http://trains-and-zeppelin.wikispaces.com/file/view/iron_cab.png/394558462/iron_cab.png", "", "Iron Cab"],
    "helicopter": ["http://trains-and-zeppelin.wikispaces.com/file/view/helicopter.png/394558492/helicopter.png", "", "Helicopter"],
    "steel_ingot": ["http://trains-and-zeppelin.wikispaces.com/file/view/itemSteelIngot.png/344002548/itemSteelIngot.png", "", "Steel Ingot"],
    "refined_fuel": ["http://trains-and-zeppelin.wikispaces.com/file/view/refinedFuel.png/394558514/refinedFuel.png", "", "Refined Fuel"],
    "signal": ["http://trains-and-zeppelin.wikispaces.com/file/view/signalItem.png/344073450/signalItem.png", "", "Signal"],

    "minecartwork": ["http://trains-and-zeppelin.wikispaces.com/file/view/WorkCart.png/394557990/WorkCart.png", "", "Work train"],
    "minecarttender": ["http://trains-and-zeppelin.wikispaces.com/file/view/tenderItem.png/344077932/tenderItem.png", "", "Tender"],
    "minecartchest": ["http://trains-and-zeppelin.wikispaces.com/file/view/freightCartItem.png/344078002/freightCartItem.png", "", "Freight car"],
    "minecartpower": ["http://trains-and-zeppelin.wikispaces.com/file/view/steamLocoItem.png/344073514/steamLocoItem.png", "", "Steam Locomotive"],
    "minecartloco3": ["http://trains-and-zeppelin.wikispaces.com/file/view/smallSteamLocoItem.png/344073454/smallSteamLocoItem.png", "", "Small Steam Locomotive"],
    "minecartloco4": ["http://trains-and-zeppelin.wikispaces.com/file/view/USFL_98%28US%29.png/394557838/USFL_98%28US%29.png", "", "USFL 98 (U.S.)"],
    "minecartbuilder": ["http://trains-and-zeppelin.wikispaces.com/file/view/tracksBuilderItem.png/344073456/tracksBuilderItem.png", "", "Tracks Builder"],
    "minecartcaboose": ["http://trains-and-zeppelin.wikispaces.com/file/thumbnail/cabooseItem.png/344073524?size=32", "", "Caboose"],
    "minecartgrain": ["http://trains-and-zeppelin.wikispaces.com/file/view/freightGrainItem.png/344073466/freightGrainItem.png", "", "Grain hopper"],
    "minecartwatertransp": ["http://trains-and-zeppelin.wikispaces.com/file/view/tankCartItem.png/344073480/tankCartItem.png", "", "Tank car"],
    "minecartwood": ["", "", "Wood transport"],
    "minecartpassenger2": ["http://trains-and-zeppelin.wikispaces.com/file/view/passenger2Item.png/344077880/passenger2Item.png", "", "Passenger car"],
    "minecarttram": ["http://trains-and-zeppelin.wikispaces.com/file/view/tramItem.png/344077940/tramItem.png", "", "Tram"],
    "minecartspeed": ["http://trains-and-zeppelin.wikispaces.com/file/view/highSpeedtem.png/344075142/highSpeedtem.png", "", "High Speed train"],
    "minecarteu07": ["http://trains-and-zeppelin.wikispaces.com/file/view/eu07Item.png/344073566/eu07Item.png", "", "EU07 (Pol.)"],
    "minecartshunter": ["http://trains-and-zeppelin.wikispaces.com/file/view/shunterItem.png/344073534/shunterItem.png", "", "Shunter (U.K.)"],
    "minecartvl10": ["http://trains-and-zeppelin.wikispaces.com/file/view/vl10Item.png/344073560/vl10Item.png", "", "VL10 (S.U.)"],
    "minecarttramwood": ["", "", "Wooden Tram"],
    "minecartchme3": ["http://trains-and-zeppelin.wikispaces.com/file/view/chme3item.png/344073532/chme3item.png", "", "ChME3 (U.S.)"],
    "minecartheavysteam": ["http://trains-and-zeppelin.wikispaces.com/file/view/heavySteamLocoItem.png/344073548/heavySteamLocoItem.png", "", "Heavy Steam locomotive"],
    "minecarttenderheavy": ["http://trains-and-zeppelin.wikispaces.com/file/view/heavyTenderItem.png/344078022/heavyTenderItem.png", "", "Heavy Tender"],
    "minecartflatcart": ["http://trains-and-zeppelin.wikispaces.com/file/view/flatCartItem.png/344073508/flatCartItem.png", "", "Flat car"],
    "minecarthighspeedcar": ["http://trains-and-zeppelin.wikispaces.com/file/view/highSpeedPassengerCartItem.png/344073578/highSpeedPassengerCartItem.png", "", "High speed car"],
    "minecartnewhighspeedloco": ["http://trains-and-zeppelin.wikispaces.com/file/view/highSpeed2Item.png/344075138/highSpeed2Item.png", "", "High speed locomotive"],
    "minecartfreightcart2": ["http://trains-and-zeppelin.wikispaces.com/file/view/freightCart2Item.png/344078000/freightCart2Item.png", "", "Freight wagon"],
    "minecartopenwagon": ["http://trains-and-zeppelin.wikispaces.com/file/view/openWagonItem.png/344073528/openWagonItem.png", "", "Open wagon"],
    "minecarttankwagon": ["", "", "Tank wagon (U.S.)"],
    "minecartjukeboxcart": ["http://trains-and-zeppelin.wikispaces.com/file/view/jukeBoxCartItem.png/344077866/jukeBoxCartItem.png", "", "Juke box"],
    "minecartstockcar": ["http://trains-and-zeppelin.wikispaces.com/file/view/stockCartItem.png/344073520/stockCartItem.png", "", "Stock car"],
    "minecartcaboosework": ["http://trains-and-zeppelin.wikispaces.com/file/view/workCabooseItem.png/344073554/workCabooseItem.png", "", "Work Caboose"],
    "minecartpassenger5": ["http://trains-and-zeppelin.wikispaces.com/file/view/passenger5Item.png/344075148/passenger5Item.png", "", "Passenger car"],
    "minecarttankwagon2": ["", "", "Tank wagon"],
    "minecartpassengerblue": ["http://trains-and-zeppelin.wikispaces.com/file/view/passengerBlue.png/394557804/passengerBlue.png", "", "Passenger car"],
    "minecartgp7red": ["", "", "GP-7 (U.S.)"],
    "minecartgp40alaska": ["http://trains-and-zeppelin.wikispaces.com/file/view/GP40Item.png/344078016/GP40Item.png", "", "GP40 Alaska Railroad (U.S.)"],
    "minecartflatcartsu": ["http://trains-and-zeppelin.wikispaces.com/file/view/flatcar-su.png/394558468/flatcar-su.png", "", "Flatcart (S.U.)"],
    "minecartflatcartus": ["http://trains-and-zeppelin.wikispaces.com/file/view/flatCartUSItem.png/344073508/flatCartUSItem.png", "", "Flatcart (U.S.)"],
    "minecartboxcartus": ["", "", "Box cart (U.S.)"],
    "minecartfreighthopperus": ["", "", "Hopper wagon (U.S.)"],
    "minecarttankwagonus": ["", "", "Tank wagon (U.S.)"],
    "minecartflatcartwoodus": ["", "", "Platform cart wood (U.S.)"],
    "minecartfreightcartus": ["", "", "Freight car (U.S.)"],
    "minecartfreightcartsmall": ["", "", "Small Freight car"],
    "minecartlococherepanov": ["", "", "Cherepanov (S.U.)"],
    "minecartminetrain": ["", "", "Minecart"],
    "minecartlocominetrain": ["", "", "Cart hauler"],
    "minecartsteamredtender": ["", "", "Tender"],
    "minecartfreightwood2": ["http://trains-and-zeppelin.wikispaces.com/file/view/freightWoodItem.png/344073458/freightWoodItem.png", "", "Wood transport"],
    "minecartcaboose3": ["", "", "Caboose"],
    "minecartpassenger7": ["", "", "Passenger car"],
    "minecartfreightclosed": ["", "", "Freight car closed"],
    "minecartfreightopen2": ["", "", "Freight car"],
    "minecartlocomogulblue": ["", "", "Mogul (U.S.)"],
    "minecartlocoforneyred": ["", "", "Forney (U.S.)"],
    "minecartlocobr01_db": ["", "", "BR01 (DB)"],
    "minecartmailwagon_db": ["", "", "Mail Wagon (DB)"],
    "minecartfreightwagon_db": ["", "", "Freight wagon"],
    "minecartpassenger8_1class_db": ["", "", "Passenger cart - first class (DB)"],
    "minecartpassenger9_2class_db": ["", "", "Passenger cart - second class (DB)"],
    "minecartlocobr80_db": ["", "", "BR80 (DB)"],
    "minecarttenderbr01_db": ["", "", "BR01's Tender (DB)"],
    "minecartflatcartrail_db": ["", "", "Rail transport (DB)"],
    "minecartflatcart_db": ["", "", "Flat car (DB)"],
    "minecartflatcartlogs_db": ["", "", "Wood transport (DB)"],
    "minecartfreightgondola_db": ["", "", "Freight Gondola (DB)"],
    "minecarttankwagon_db": ["", "", "Tank Wagon (DB)"],
    "minecartlocosd70": ["", "", "SD70 Union Pacific (U.S.)"],
    "minecartrotativedigger": ["", "", "Rotary excavator"],
    "minecartlocoer": ["", "", "USSR 0-5-0"],
    "minecarttenderer": ["", "", "USSR 0-5-0 tender"],
    "minecartlocou57": ["", "", "U-57"],
    "minecarttenderu57": ["", "", "U-57 tender"],
    "minecartlocosd40": ["", "", "SD40 Santa Fe (U.S.)"],
    "minecartfreightcenterbeam_empty": ["", "", "Freight car"],
    "minecartfreightcenterbeam_wood_1": ["", "", "Wood transport"],
    "minecartfreightcenterbeam_wood_2": ["", "", "Wood transport"],
    "minecartfreighttrailer": ["", "", "Freight trailer"],
    "minecartfreightwellcar": ["", "", "Freight wellcar"],
    "minecartkof_db": ["", "", "Kof (DB)"],
    "minecartv60_db": ["", "", "V60 (DB)"]
};

export default MAPS; 